### ISSUE TITLE
:is() selector does not work in chrome < 88

### ISSUE THREAD

**Issue by jurijzahn8019** [calebdwilliams/element-internals-polyfill#118]
Hi there,

I have tried this project in different browsers and discovered a problem, especially in Chromes

as per Caniuse, chrome supports ElementInternals from 77: https://caniuse.com/mdn-api_elementinternals

but ":is" from 88: https://caniuse.com/?search=%3Ais

so in browsers < 77 the polyfill fails with "not a valid selector"

same in safari < 14

I need to support Chrome browsers >= 63 any Safari >= 11. I can babel modern syntax like optional changing etc. But ":is" is not that simple.

The question is if it would be possible to rewrite the query with "flatMap" and "matches" (I can PR this).

And whether it even is considered an issue.

Thanks in advance.

https://github.com/calebdwilliams/element-internals-polyfill/blob/8aa2b3d51db00d32085153b003fdffcd527eebcd/src/utils.ts#L133

**Comment by calebdwilliams** [comment]
Feel free to open a PR.

**Comment by calebdwilliams** [comment]
Should be fixed in the latest version.
