### ISSUE TITLE
[feature request] Type Definition for TypeScript

### ISSUE THREAD

**Issue by TechQuery** [calebdwilliams/element-internals-polyfill#13]
This polyfill is great! So I'm working on integrating **Element Internals** into my **Web Components** framework [_WebCell_](https://web-cell.dev/), but I found no `.d.ts`...

@calebdwilliams

**Comment by calebdwilliams** [comment]
Hey @TechQuery, I’ll try to get to this ASAP.

**Comment by calebdwilliams** [comment]
OK @TechQuery, I've actually worked to migrate the repo over to TypeScript (although I'm generally not a huge TypeScript fan, but wanted to give it a go for this project). Can you check out the [ts](https://github.com/calebdwilliams/element-internals-polyfill/tree/ts) branch and build that and let me know if it works for you?

**Comment by calebdwilliams** [comment]
Alright, I confirmed this is working, you can [see it in action on this demo on StackBlitz](https://stackblitz.com/edit/element-itnernals-types).

**Comment by TechQuery** [comment]
@calebdwilliams It works, thanks!
