### ISSUE TITLE
Multiple form elements with same name

### ISSUE THREAD

**Issue by brion-fuller** [calebdwilliams/element-internals-polyfill#26]
If you have multiple form elements with the same name, the values are not appended to the form.

Example:
```
<form>
    <input checked type="checkbox" name="name"/>
    <input checked type="checkbox" name="name" value="greg" />
</form>
```

Expected:
In the example above, I will see two entries in the formData object resulting in `name=['on','greg']`

Current behavior:
I will only receive the last elements value `name='greg'`.

**Comment by calebdwilliams** [comment]
Hey @brion-fuller, I'm finally getting around to this one. I think Chrome's implementation is a bit different than you might expect. Given:

```html
<form id="form">
  <x-el v="foo" name="foo"></x-el>
  <x-el v="bar" name="foo"></x-el>
  <button type="submit">submit</button>
</form>

<script>
class El extends HTMLElement {
  static get formAssociated() {
    return true;
  }
  internals = this.attachInternals();
  connectedCallback() {
    const v = this.getAttribute('v');
    this.internals.setFormValue(v);
    this.innerHTML = v;
  }
}

customElements.define('x-el', El);

form.addEventListener('submit', e => {
  e.preventDefault();
  console.log(new FormData(e.target).get('foo'));
});
</script>
```

you should only get one value out of the `console.log` you will only get `foo`. I have a [reproduction of this on CodePen](https://codepen.io/calebdwilliams/pen/gOgNXQK?editors=1010). I believe this is working as expected. 

Although this brings up a great question for the spec: If users want to set multiple values to the same name, how should that be accomplished?

Thoughts? Even if you this polyfill is working as expected, I agree this is a logic gap in the API that we should work together to raise to the spec authors.

**Comment by brion-fuller** [comment]
Actually I thought this at first too.  If you update the `get` to `getAll` you will see all the values set.  `get` will always just return the first value but the others still exist.
```html
<form id="form">
  <x-el v="foo" name="foo"></x-el>
  <x-el v="bar" name="foo"></x-el>
  <button type="submit">submit</button>
</form>

<script>
class El extends HTMLElement {
  static get formAssociated() {
    return true;
  }
  internals = this.attachInternals();
  connectedCallback() {
    const v = this.getAttribute('v');
    this.internals.setFormValue(v);
    this.innerHTML = v;
  }
}

customElements.define('x-el', El);

form.addEventListener('submit', e => {
  e.preventDefault();
  console.log(new FormData(e.target).getAll('foo'));
});
</script>
```

**Comment by calebdwilliams** [comment]
Is the polyfill behaving as expected then?

**Comment by brion-fuller** [comment]
Ah this is working in Firefox.  I will close.  I was on an older version.
