### ISSUE TITLE
The event emitted when an element is invalid is 'false'

### ISSUE THREAD

**Issue by enjoythelive1** [calebdwilliams/element-internals-polyfill#3]
So, in the in this [line](https://github.com/calebdwilliams/element-internals-polyfill/blob/3995fa2f4b3291819c6d694b7919402c94749c71/src/element-internals.js#L36) the invalid event that is supposed to be emitted has an `"false"` name, instead of the probably intended `valid` or `invalid`, so this polyfill is not triggering the `invalid`event correctly.

**Comment by calebdwilliams** [comment]
This was fixed in 0.0.18.

**Comment by enjoythelive1** [comment]
This is funny, I have already made a PR to fix this. Thanks for the fix.

Also, it would be nice to have this covered by a test.

**Comment by calebdwilliams** [comment]
Yeah, I'm planning on redoing the testing entirely here soon. I just hopped on and fixed these real quick while I was listening to a meeting. 

PRs are always welcome, just let me know you want to take it on and I will assign the fix to you.

If you see anything else that's off or a missing feature, I'd be thrilled to accept a contribution of field another issue.
