### ISSUE TITLE
form.reportValidity() and form.checkValidity() are not influenced by component validity

### ISSUE THREAD

**Issue by lucaelin** [calebdwilliams/element-internals-polyfill#30]
Hey, thank you for this great polyfill! I am looking forward to browser implementation coming in!

During development I noticed a few inconsistencies regarding validity checking called on the associated form element.
Specifically `form.reportValidity()` and `form.checkValidity()` both return `true` even if the internals validity is set to false. Additionally they do not cause the components `invalid` event to fire.

The following glitch should show a reproducible inconsistency https://glitch.com/edit/#!/eminent-grape-soul (tested using FF 89 and Chome 90).

Secondly, I am curious about the inconsistency when hitting the in-form submit button. It appears that native inputs are preferred by the polyfill and no check happens on the custom inputs if one of the native ones is already invalid. This is also different on Chrome.
 
I also realized, that the `invalid` selector is not supported. Maybe this would be great as an addition to the readme? 
 
*edit: I accidentally tabbed out of the input and hit enter, so the initial issue was empty

**Comment by calebdwilliams** [comment]
Hey @lucaelin, thanks for the insight here. I've made a few updates that I think will address your issues, take a look at version `0.1.33`. I _might_ have missed something, but I think we're in a good place now.

I'm going to close this issue for now, if there are anything I missed, please open a new issue.
