### ISSUE TITLE
lit-html + attachInternals inside constructor causes some elements to not associate correctly

### ISSUE THREAD

**Issue by lucaelin** [calebdwilliams/element-internals-polyfill#31]
I found another inconsistency while using lit-html to render associated-components.
Basically, if you run `attachInternals()` inside the constructor, it fails to initialize when using a lit-html template inside another template. 

I do not know enough about the internals of lit-html but I assume it is caused by the additional step of `<template>`ing the component, without any connection to the outer `form` and later connecting it to the actual DOM. 
Moving `attachInternals()` over into the `connectedCallback()` works reliably.

I again created a glitch with a reproduction: https://glitch.com/edit/#!/dog-glib-beluga?path=script.js%3A12%3A0

Thank you so much for your work!

**Comment by calebdwilliams** [comment]
Looks like when the `ElementInternals` instance is constructed it's still in a context of a `DocumentFragment`, so it doesn't initialize right away. But, this also never triggers the mutation observer when it's actually connected to the parent fragment. Not sure how to fix this. I'll keep looking at it.

**Comment by calebdwilliams** [comment]
OK, I was able to address this my attaching a separate `MutationObserver` to the `DocumentFragment`, let me know if this is working for you in version `0.1.34`. Thanks for raising this issue.

**Comment by lucaelin** [comment]
It's working great! 🎉 Thank you so much!
