### ISSUE TITLE
elements undefined 

### ISSUE THREAD

**Issue by reno1979** [calebdwilliams/element-internals-polyfill#34]
Thanx for the polyfill! 

I did manage to break it though  (did not mean to :) )

I'm using multiple forms, not all forms contain form associated custom elements. 

Therefor the used weakmap does not contain each form. 

On a form change event , this breaks: 

https://github.com/calebdwilliams/element-internals-polyfill/blob/dc043393825d53ad3105e295d58d77b7e5ac5600/src/utils.ts#L216

It does not validate the elements variable, and this is empty in our case

**Comment by calebdwilliams** [comment]
Hey, would you mind creating a minimal reproduction?

**Comment by reno1979** [comment]
no problem: 

https://jsfiddle.net/uy2f58on/2/

I wanted to see if validating the elements var was enough but I was not able to convert the typescript code on the machine I'm working on (restrictions), so I used the index.js to rebuild the modules (es6/7 format.)

**Comment by calebdwilliams** [comment]
Hey @reno1979, give `element-internals-polyfill@0.1.41` a try and see if things are behaving as expected. Closing this for now.
