### ISSUE TITLE
lit v2 - hidden inputs will never be deleted?

### ISSUE THREAD

**Issue by chrschdev** [calebdwilliams/element-internals-polyfill#36]
Hey,

I invoke the setFormValue method multiple times for a custom checkbox component, e.g. on connected callback or on attribute change callback. The polyfill then seems to add for each invocation a new hidden input field, but will never remove the existing ones before. Have debugged some parts of your code, code lines like "hiddenInput.remove() will be invoked, but the hidden input field will never be removed from DOM properly.

Is this an known issue, or any recommendations how to handle that?

I am using lit with version  2.0.0-rc.2 and the latest version of this element internals polyfill.

Thanks

**Comment by calebdwilliams** [comment]
Nope, that shouldn’t be happening. I’ll look in to it.

**Comment by calebdwilliams** [comment]
Hey @chrschdev, I can't seem to reproduce this particular issue. Would you mind creating a reproduction for me in CodePen? It doesn't have to be super complex, I just want to observe the behavior and see if I can figure out what's happening exactly.

**Comment by calebdwilliams** [comment]
Hey @chrschdev, [here's the reproduction I was using](https://codepen.io/calebdwilliams/pen/abWEpmW?editors=0010). The results are consistent across Chrome and Firefox. The input is removed if and only if the `internals.setFormValue` method is called with `null` (calling it with an empty string leaves an empty `input[type="hidden"]`.

There _might_ be a bug here, but based on the information in your original post, I don't know the full steps to reproduce the issue. If you can provide a reproduction and/or steps to reproduce, I'm more than happy to try to fix this. Until then I'm going to close this issue (again, more than happy to re-open it if there is actually a bug).

Thanks for using this package!

**Comment by chrschdev** [comment]
Hey @calebdwilliams ,
thanks for fixing that bug with version 0.1.42. Works now!

Kindly regards
Christoph
