### ISSUE TITLE
"disabled" attribute won't be observed

### ISSUE THREAD

**Issue by chrschdev** [calebdwilliams/element-internals-polyfill#37]
Hey @calebdwilliams,
i have seen that the "disabled" attribute is on the filter list of the MutationObserver. Is there any reason for that?
I can't see in the official documentation any information about that.

To reproduce my issue with that:

1. create a input of type checkbox, add attributes `checked` and  `value="test"`
2. in browser, use the inspector and add a `disabled` attribute on-the-fly

expected behaviour:
1. it will add a hidden input
2. it will then remove again the hidden input, because disabled checkboxes will never submit their values

but current behavior:
1. it will add a hidden input
2. the hidden input will stay, and the value of the checkbox will be submitted

In Chrome, where the polyfill will not be used, it behaves like expected, the value of a disabled checkbox will not be submitted.

Thank you
Christoph

**Comment by chrschdev** [comment]
Ah was only a misunderstanding from my side. The right way is to set the form value to null in my application, and observe the disabled attribute by myself.

Closed!

**Comment by calebdwilliams** [comment]
I’d actually love to know what is the default Chrome behavior here and if the polyfill aligns with it. I want to dive into this a bit.
