### ISSUE TITLE
Internals setValidity calls reportValidity, but that is not part of the expected behavior 

### ISSUE THREAD

**Issue by enjoythelive1** [calebdwilliams/element-internals-polyfill#4]
The behavior of `setValidity` in the ElementInternals polyfill does not match the behavior described in the [`ElementInternals` spec](https://html.spec.whatwg.org/multipage/custom-elements.html#dom-elementinternals-setvalidity).

It calls `reportValidity`, but it should not.

**Comment by calebdwilliams** [comment]
This is fixed in 0.0.17. Thanks for letting me know.
