### ISSUE TITLE
Disabled elements don't have `:disabled` or [internals-disabled] matchers added 

### ISSUE THREAD

**Issue by andrico1234** [calebdwilliams/element-internals-polyfill#41]
Hi Caleb, Thanks for the wonderful Polyfill

I'm working on a UI web component library and have a test suite that runs tests in Chromium, WebKit, and Firefox.

For the most part, the element-internal-polyfill works great, but I'm having trouble using it with disabled elements. 

In short, when an form-associated custom element has a `disabled` attribute, Chrome automatically applies the `:disabled` psedo-class, but this doesn't happen to the elements that get element internals behaviour from the polyfill.

I tried creating a sandbox, but couldn't get it working so I made a [repro-repo](https://github.com/andrico1234/temp-el-internal-repro) instead. 

If you clone it, install dependencies and run `npm test`, you should be able to see what I mean.

I can give you more details if you want, but I'd also love to contribute a fix for this! 

Ctrl + F ":disabled" in google's [form participation docs](https://docs.google.com/document/d/1JO8puctCSpW-ZYGU8lF-h4FWRIDQNDVexzHoOQ2iQmY/edit#) should also give more context about the expected disabled behaviour:

EDIT:

The last section of the docs says:

> It is currently impossible to set form states to :invalid and :valid so this polyfill replaces those with the [internals-invalid] and [internals-valid] attributes on the host element. The proper selector for invalid elements will be :host(:invalid), :host([internals-invalid]).

I imagine the same goes for disabled too?

**Comment by andrico1234** [comment]
Could it be as straight forward as removing the `disabled` attribute from the MutationObserver filter, and running a callback whenever the attribute changes that toggles the `internals-disabled` class?

**Comment by andrico1234** [comment]
Note: I tried removing `disabled` as an attribute in the MutationObserver filter, but it caused the tests to run where the Chrome behaviour is now out of sync with the other browsers.

My thoughts are leading me to believe that Firefox + Webkit aren't setting the :disabled pseudo-class because it should only added to certain [form inputs or form-associated elements](https://html.spec.whatwg.org/multipage/semantics-other.html#concept-element-disabled). Do you know where we might want to set the disabled pseudo-class?

I'm also trying to dive into the Chromium repo to see if I can find anything, but am having no luck.

**Comment by andrico1234** [comment]
friendly bump @calebdwilliams

**Comment by calebdwilliams** [comment]
This was released in version 0.1.44
