### ISSUE TITLE
[docs] examples of using the AOM properties

### ISSUE THREAD

**Issue by michaelwarren1106** [calebdwilliams/element-internals-polyfill#44]
Im definitely interested in the AOM properties of this polyfill, but I dont see any examples in the README of how to set it up inside a custom element.

i would assume its something like calling `initAom` from https://github.com/calebdwilliams/element-internals-polyfill/blob/master/src/aom.ts#L43 in the custom element constructor, but it would be good for an example to be provided.

If I'm right about that, I'd be glad to send a small PR to update the readme to include the examples :)

**Comment by calebdwilliams** [comment]
Good callout, fortunately you don't even need to do that, you can simply use the AOM setters, so:

```typescript
class Whatever extends HTMLElement {
  static formAssociated = true;

  internals = this.attachInternals();

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.internals.ariaBusy = true;
  }
}
```

should suffice.

**Comment by calebdwilliams** [comment]
Added an example to the README.
