### ISSUE TITLE
Latest Firefox Developer Edition/nightlies break polyfill

### ISSUE THREAD

**Issue by jrunning** [calebdwilliams/element-internals-polyfill#45]
This is an issue only affecting Firefox Developer Edition and experimental/nightly versions so I don't know if I'd call it a bug, but it tripped me up so I thought it might be useful to others to mention it here.

<details>
<summary>
Today I updated Firefox Developer Edition from 91.0 to 93.0b3 and discovered that form-associated custom elements are no longer being polyfilled.
</summary>

Specifically, after doing `this._internals = this.attachInternals()` I found that `this._internals.setFormValue()` was throwing the error `Uncaught TypeError: this._internals.setFormValue is not a function`. The value of `this._internals` was an EventInternals object, as expected, but it didn't have a `setFormValue` method. It had but a single property, `shadowRoot`.

What's happened is that ElementInternals is _partially_ (but mostly not) implemented in Firefox, so `window.ElementInternals` exists and element-internals-polyfill's check for its absence fails and the polyfill doesn't polyfill. This incomplete implementation lives behind a configuration flag called `dom.webcomponents.elementInternals.enabled`, which is set to `false` in standard Firefox releases but, as of 93.0, set to `true` in Firefox Developer Edition and (I think) experimental/nightly releases.

Firefox [bug 1552313](https://bugzilla.mozilla.org/show_bug.cgi?id=1552313) is related to this, but I'm not sure it's _the_ relevant bug.
</details>

The fix—i.e. to make `window.ElementInternals` `undefined` again so the polyfill does its work—is to go to [`about:config`](https://support.mozilla.org/en-US/kb/about-config-editor-firefox) and search for `dom.webcomponents.elementInternals.enabled` and toggle it to `false`.

**Comment by calebdwilliams** [comment]
I definitely think this is something to track (I will keep this issue open), but until Nightly enables `ElementInternals` without a flag, I think I'll leave this alone. It doesn't really make sense to wrestle with something that experimental and I assume that any one who knows enough to turn that flag on will have accepted the risks of doing so.
