### ISSUE TITLE
form:valid and form:invalid CSS selectors inconsistent with validity of form-associated custom elements

### ISSUE THREAD

**Issue by brandonmosher** [calebdwilliams/element-internals-polyfill#48]
form:valid does match/form:invalid does not match a form with an invalid form-associated custom element.

I created a quick patch because I needed this functionality in a project I was working on. My solution was to attach an input event listener to the form that toggles "internals-valid" and "internals-invalid" attributes on the form based on the result of form.checkValidity(). You can then select the form as expected using some variation the following:

form:is(:invalid, [internals-valid])
form:is(:valid:not([internals-invalid]), [internals-valid])

I'm not sure whether there is a better way to implement this. If this seems like a reasonable solution, I'd be happy to submit a PR!

**Comment by calebdwilliams** [comment]
Closing due to the merging of #49
