### ISSUE TITLE
Too many `invalid` events

### ISSUE THREAD

**Issue by xdev1** [calebdwilliams/element-internals-polyfill#53]
It seems that the polyfill dispatches more `invalid` events than expected.
Please have a look a the following demo.
If you enter something in the input field you'll see that in firefox on each input an `invalid` event is fired, while in Chrome it's not (the latter is the correct behavior, I guess).
https://codesandbox.io/s/nifty-glade-vm1ju?file=/src/index.js

Used FF version: 95.0.1 (Windows), used Chrome version: 96.0.4664.110 (Windows)

**Comment by calebdwilliams** [comment]
This has been fixed in `element-internals-polyfill@0.1.50`.
