### ISSUE TITLE
README lacks description of currently supported features

### ISSUE THREAD

**Issue by web-padawan** [calebdwilliams/element-internals-polyfill#6]
The line before "Current Limitations" section seems to be incomplete:

> The currently-supported features of ElementInternals for form-associated custom elements are

Would you like to add a list of features, or maybe remove it for now?

**Comment by calebdwilliams** [comment]
I've updated the docs a bit to describe the currently-supported features. Let me know if you have any comments or critiques, but I'm going to close this issue for now. Thanks for pointing this out!
