### ISSUE TITLE
Polyfill checkValidity evaluates too false when component is disabled

### ISSUE THREAD

**Issue by rhelling** [calebdwilliams/element-internals-polyfill#65]
When a formAssociated web component is disabled it doesn't report as valid when using the polyfilled version. The current implementation within the latest versions of Firefox and Chrome acts differently. To demonstrate this behaviour I created this example code sandbox:

https://codesandbox.io/s/litelement-formcontrol-example-d3jbut

When you open de sandbox directly in a browser without support for element internals the checkValidity evaluates too false in Chrome and Firefox checkValidity evaluates to true. I intentionally left the input in the Shadow DOM enabled so fiddling with the components value is possible.

https://d3jbut.csb.app/

**Comment by calebdwilliams** [comment]
Pretty simple fix, looks like I just need to make sure that we need to return `true` if `internals.willValidate === false` for check and report validity. This has been released in `element-internals-polyfill@1.0.2`.

**Comment by calebdwilliams** [comment]
Here's a [forked version of your project using the latest polyfill version](https://codesandbox.io/s/litelement-formcontrol-example-forked-m0vvup).
