### ISSUE TITLE
Support shadydom in IE11

### ISSUE THREAD

**Issue by zhoukekestar** [calebdwilliams/element-internals-polyfill#68]
Hi, thanks for your awesome project ! We try it in IE 11, run most code correctly but find some wrong in webcomponents polyfill.

You can find detail in this issue: https://github.com/webcomponents/polyfills/issues/504 .

I think it can be fixed very simple by modify `attachShadowObserver` like this:

```js
 try {
    observer.observe(shadowRoot, observerConfig);
  } catch (err) {
    console.info('observe shadowRoot to this');
   // we can just observe parent element in IE11, the code will run correctly.
    observer.observe(this, observerConfig);
  }
```

**Comment by zhoukekestar** [comment]
Yes, do different logic by detect shadydom is a better way.

**Comment by calebdwilliams** [comment]
@zhoukekestar can you try `element-internals-polyfill@1.1.3`

**Comment by zhoukekestar** [comment]
Test `1.1.3` on IE 11, and it works now. Thanks a lot.
