### ISSUE TITLE
Unmodified form input not posted

### ISSUE THREAD

**Issue by pjdevries** [calebdwilliams/element-internals-polyfill#69]
Hi @calebdwilliams. Thanx for this polyfill.

I am a programmer but not quite a JS expert and probably missing the obvious. So please be gentle :)

I have a form with a regular `<input>` field and an `<input>` wrapped in a minimalistic web component. Both fields get an initial `value`, that show up nicely on the form. When modifying the initial values and submitting the form, the new values show up in my POST data as expected. However, if I _don't_ modify the initial values, the initial value of the regular `<input>` is present in the POST data but the initial value of the web component's `<input>` is not. Why is that and is there a way to have unmodified web component data posted as well?

**Comment by calebdwilliams** [comment]
It’s difficult to say without a reproduction. Could you make one with CodePen and I’ll take a look?

**Comment by calebdwilliams** [comment]
Hmmm, it definitely should. Can you make sure your component has a name attribute?

**Comment by pjdevries** [comment]
Yes, it has a name attribute. I realize it's not ideal, but let me post my code here nevertheless:

The JS component code:

```js
import "element-internals-polyfill";

class TestComponent extends HTMLElement {
    #shadow;

    // Enable ElementInternals interface, to allow the component to behave
    // more or less like a proper form element, among other things.
    static get formAssociated() {
        return true;
    }

    constructor() {
        super();

        // Attach ElementInternals interface.
        this.internals = this.attachInternals();

        this.render();
    }

    render() {
        this.#shadow = this.attachShadow({mode: 'closed'});

        this.#shadow.innerHTML = `
            <style>
                input { 
                    width: auto; 
                }
            </style>
            
            <input type="text" placeholder="Type some text" />
        `;
    }

    connectedCallback() {
        this.#shadow.querySelector('input').addEventListener('input', e => {
            this.setValue(e.target.value);
        });
    }

    static get observedAttributes() {
        return [
            'name',
            'value'
        ];
    }

    attributeChangedCallback(property, oldValue, newValue) {
        if (oldValue === newValue) {
            return;
        }

        switch (property) {
            case 'value':
                this.setValue(newValue);
                break;

            default:
                this[property] = newValue;
        }
    }

    setValue(value) {
        this.value = value;
        this.#shadow.querySelector('input').value = value;
        this.internals.setFormValue(value);
    }
}

customElements.define('obix-test', TestComponent);
```

And for completeness the PHP page:

```php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web Component</title>

    <script src="js/TestComponent.js"></script>
</head>

<?php
if (isset($_POST['formData']))
{
	echo '$_POST: ' . print_r($_POST, true) . '<br />';
}
?>

<body>
<form name="myForm" id="myForm" action="/index2.php" method="post">
    <label for="regular">Regular</label>
    <input id="regular" type="text" placeholder="Type something" name="formData['regular']" value="Regular text" />

    <label for="web-component">Web Component</label>
    <obix-test id="web-component" name="formData['web-component']" value="Web component text"></obix-test>

    <button type="submit">Submit</button>
</form>
</body>
```

**Comment by pjdevries** [comment]
Hi @calebdwilliams. Any new insights on this one. Or am I being to impatient now?

**Comment by calebdwilliams** [comment]
He @pjdevries this is working as expected. I ran a simple PHP server locally with your files and am getting the expected result in Chrome, Firefox and Safari. What browser are you testing with?

**Comment by pjdevries** [comment]
Hi @calebdwilliams. 

I'm testing with FireFox on a local server as well. A docker based Apache server, running the browser from within Ubuntu. Using an X server from my WSL2 system, to be exact :) Are you sure we're both testing the same thing. What I mean is, did I explain well enough which problem I experience?

With the code I posted above, this is the literal `$_POST` output I get when submitting the form, without modifying either of the  field values:

```
$_POST: Array ( [formData] => Array ( ['regular'] => Regular text ) ) 
```
As you can see, only the (default) value of the `regular` field is contained in `$_POST`. 

However, when changing the value of the `web-component` field, this is the output I get:

```
$_POST: Array ( [formData] => Array ( ['regular'] => Regular text ['web-component'] => Modified web component text ) ) 
```
This time `$_POST` also contains the (modified) value of the  `web-component` field.

Is this different in your test setup? Do you get both the `regular` and `web-component` input values in both cases?

**Comment by calebdwilliams** [comment]
My steps and results:

1. Run `php -S localhost:9000` on my computer with the above code
2. Open localhost:9000
3. Click the submit button
4. See output `$_POST: Array ( [formData] => Array ( ['regular'] => Regular text ['web-component'] => Web component text ) )`

I get this same behavior on 

- Chrome 100
- Firefox 99.0.1
- Safari 14.1.1

As far as I can tell this is the expected behavior. When modifying the web component value and running submit, I get the modified value to show up in the PHP output.

**Comment by pjdevries** [comment]
Yes, that's the expected result. I'll do it the way you did tomorrow and let you know what happens.

**Comment by pjdevries** [comment]
Unfortunately my lack of sufficient JS knowledge is now playing tricks on me. When running the script with the built-in web server, like you did, the Web Component does not even load properly, failing with the dreaded `Uncaught SyntaxError: expected expression, got '<'` error.

I don't have a clue why it works as expected in your setup and it doesn't in mine and my lack of JS knowledge and experience does not make it any easier. But I don't want to take up any more of your valuable time. Especially if I am the only one experiencing this problem. So let's leave it at this, while I try to think of a less challenging solution for my project.

Thank you very much for your time.
