### ISSUE TITLE
Custom elements are not polyfilled when added within a subtree

### ISSUE THREAD

**Issue by sipris** [calebdwilliams/element-internals-polyfill#73]
## Example
Consider the following code:
```js
const form = document.createElement('form');
const control = new CustomControl();
form.appendChild(control);
document.body.appendChild(form);
```
The `control` will not be polyfilled. Executing `control.internal.setValidity(..)` will throw:
 
 ```
Uncaught TypeError: items is undefined    index.js:74:41
    setFormValidity index.js:74
    reconcileValidity index.js:283
    setValidity index.js:509
    ...
```

## Reason
The `MutationObserver` will only check if the *added node* (which is the `form` element) is a form-associated custom element, but the subtree is not searched for form-associated custom elements, so the `control` in the example is never associated with the form.

**Comment by calebdwilliams** [comment]
Hey @sipris thanks for reporting this issue. I'm trying to duplicate the error locally, but I haven't been able to so far. [Would you mind either forking this Pen](https://codepen.io/calebdwilliams/pen/OJvaJbv?editors=0010) or giving me guidance on how to reproduce? Once I have that I will work toward a solution as quick as possible.

**Comment by sipris** [comment]
Hi @calebdwilliams, thanks for the quick response. Here is a [jsfiddle](https://jsfiddle.net/4etmjzr6/) with the issue. I might have to add that this issue is only relevant to the Safari browser.

**Comment by calebdwilliams** [comment]
This should be fixed in version 1.1.8. Can you confirm on your end?

**Comment by calebdwilliams** [comment]
OK, I [updated my original Pen with the new code and this is now working as expected](https://codepen.io/calebdwilliams/pen/OJvaJbv?editors=0010). Thanks again @sipris.

**Comment by sipris** [comment]
Hi @calebdwilliams, I confirm the fix. Thank you 👍
