### ISSUE TITLE
Enclosing fieldset's `disabled` attr does not disable polyfilled elements

### ISSUE THREAD

**Issue by bennypowers** [calebdwilliams/element-internals-polyfill#88]
Please consider https://codepen.io/bennyp/pen/KKemLEG?editors=1010

```html
<form id="form">
  <fieldset id="set" disabled>
    <legend>This fieldset controls <code>x-checkbox</code></legend>
    <label for="xcheck">Check?</label>
    <x-checkbox id="xcheck" name="checkit"></x-checkbox>
  </fieldset>
</form>
```

In this case, using GNOME Web 43.0-66-g2cd7f8ec4+ (WebKitGTK 2.38.2), with the polyfill loaded, I observed that toggling `disabled` on the fieldset had no effect on `x-checkbox`. 

**Expected**: `:disabled` or known-limitations equivalent should be applied to the FACE, mouse clicks should be prevented.

**Comment by calebdwilliams** [comment]
I'll try to work on this a bit unless you'd like to tackle it.

**Comment by bennypowers** [comment]
I can grab this one:

the MutationObserver will toggle the string value of aria-disabled on each associated child when fieldset parent's disabled changes
